import Head from 'next/head'
import HomePage from '@/components/home/home-page';


export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>


      <HomePage data={data} />

    </>
  )
}


export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json');
  console.log(events_categories);
  // const res  = await fetch('URL') ;
  // const data = await res.json();

  return {
    props: {
      data: events_categories
    }
  }
}
